### ISSUE TITLE
Crash when 'say joke' command

### ISSUE THREAD

**Issue by sriks** [sriks/pibot#4]
pibot-0 (err):     at _processSay (/home/pi/git/server/pibot/commandcenter/commandcenter.js:34:9)
pibot-0 (err):     at Object.process (/home/pi/git/server/pibot/commandcenter/commandcenter.js:80:9)
pibot-0 (err):     at _processCommand (/home/pi/git/server/pibot/pibot.js:12:8)
pibot-0 (err):     at Object.<anonymous> (/home/pi/git/server/pibot/pibot.js:49:9)
pibot-0 (err):     at Object.<anonymous> (/home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:765:28)
pibot-0 (err):     at Object.Botkit.botkit.trigger (/home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:791:49)
pibot-0 (err):     at Object.<anonymous> (/home/pi/git/server/pibot/node_modules/botkit/lib/SlackBot.js:472:34)
pibot-0 (err):     at Object.Botkit.botkit.trigger (/home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:791:49)
pibot-0 (err):     at /home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:873:32
pibot-0 (err): TypeError: Cannot call method 'randomJoke' of undefined
pibot-0 (err):     at process (/home/pi/git/server/pibot/commandcenter/commandcenter.js:85:15)
pibot-0 (err):     at _processSay (/home/pi/git/server/pibot/commandcenter/commandcenter.js:34:9)
pibot-0 (err):     at Object.process (/home/pi/git/server/pibot/commandcenter/commandcenter.js:80:9)
pibot-0 (err):     at _processCommand (/home/pi/git/server/pibot/pibot.js:12:8)
pibot-0 (err):     at Object.<anonymous> (/home/pi/git/server/pibot/pibot.js:49:9)
pibot-0 (err):     at Object.<anonymous> (/home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:765:28)
pibot-0 (err):     at Object.Botkit.botkit.trigger (/home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:791:49)
pibot-0 (err):     at Object.<anonymous> (/home/pi/git/server/pibot/node_modules/botkit/lib/SlackBot.js:472:34)
pibot-0 (err):     at Object.Botkit.botkit.trigger (/home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:791:49)
pibot-0 (err):     at /home/pi/git/server/pibot/node_modules/botkit/lib/CoreBot.js:873:32

**Comment by sriks** [comment]
Disabled joke skill.
